export const GREETING_PHRASES: Record<'hello' | 'welcomeBack', string[]> = {
  hello: [
    'Hello there...',
    'One sec.',
    'Hi there...',
    'Hey there....',
    'One moment.',
    'Hi! One sec.',
  ],
  welcomeBack: [
    'Welcome back....',
    'One sec.',
    'Welcome back! One sec.',
    'One moment.',
    'Welcome back... one sec.',
  ],
};

export const QUESTION_BRIDGE_PHRASES = [
  'Good question...',
  'That’s a good question...',
  'Good question. Let’s take a look...',
];

export const TOOL_NARRATION_PHRASES: Record<string, string[]> = {
  read_file: [
    'Let me read through {file}.', 'I’ll take a closer look at {file}.', 'Let me inspect {file}.',
    'I’m checking what’s in {file}.', 'Let me see how {file} works.', 'I’ll review {file} for context.',
    'Let me dig into {file}.', 'I’m going through {file} now.', 'Let me check the details in {file}.',
    'I’ll get familiar with {file}.', 'Let me trace through {file}.', 'I’m taking a look inside {file}.',
    'Let me understand what {file} is doing.', 'I’ll scan {file} for the relevant part.',
    'Let me read the surrounding code in {file}.', 'I’m checking {file} before we continue.',
    'Let me get some context from {file}.', 'I’ll examine the implementation in {file}.',
    'Let me see what we’re working with in {file}.', 'I’m reviewing the current state of {file}.',
    'Let me verify the logic in {file}.', 'I’ll look through {file} carefully.',
    'Let me follow what’s happening in {file}.', 'I’m reading {file} to find the right spot.',
    'Let me check how this is set up in {file}.',
  ],
  edit_file: [
    'Let me update {file}.', 'I’ll make that change in {file}.', 'Let me adjust {file}.',
    'I’m applying the update to {file}.', 'Let me refine {file}.', 'I’ll patch {file} now.',
    'Let me make the targeted edit in {file}.', 'I’m updating the relevant part of {file}.',
    'Let me edit {file}.', 'I’ll put that fix into {file}.',
    'I’m making the requested change in {file}.', 'I’ll adjust the implementation in {file}.',
    'Let me improve this part of {file}.', 'Let me apply a focused change to {file}.',
    'I’ll update the code in {file}.', 'I’m revising the relevant lines in {file}.',
    'Let me clean up {file}.', 'I’ll make the necessary adjustment in {file}.',
    'Let me incorporate that into {file}.', 'I’m modifying {file} now.',
  ],
  write_file: [
    'Let me create {file}.', 'I’ll put {file} together.', 'Let me set up {file}.',
    'I’m creating {file} now.', 'Let me add the new {file}.', 'I’ll draft {file}.',
    'Let me build out {file}.', 'I’m putting the contents of {file} in place.',
    'Let me write {file} from scratch.', 'I’ll get {file} started.', 'Let me assemble {file}.',
    'I’m adding {file} to the project.', 'Let me prepare {file}.', 'I’ll create the initial {file}.',
    'Let me lay out {file}.', 'I’m writing the new {file}.', 'Let me get {file} into place.',
    'I’ll add the implementation in {file}.', 'Let me create the new {file}.',
    'I’m setting up the structure for {file}.',
  ],
  open_file: [
    'Let me open {file}.', 'I’ll bring up {file}.', 'Let me jump to {file}.',
    'I’m opening {file} in the editor.', 'Let me navigate to {file}.', 'I’ll pull up {file}.',
    'Let me show you {file}.', 'I’m heading over to {file}.', 'Let me focus the editor on {file}.',
    'I’ll open {file}.', 'Let me highlight the relevant part of {file}.',
    'I’m bringing {file} into view.', 'Let me point you to {file}.', 'I’ll open the right section of {file}.',
    'Let me surface {file} in the editor.', 'I’m navigating to the code in {file}.',
    'Let me put {file} on screen.', 'I’ll show the relevant lines in {file}.',
    'Let me show you the relevant part of {file}.', 'I’m opening up {file} for us.',
  ],
  list_directory: [
    'Let me look around in {file}.', 'I’ll check the structure of {file}.', 'Let me see what’s inside {file}.',
    'I’m exploring {file}.', 'Let me map out {file}.', 'I’ll take a look through {file}.',
    'Let me inspect the contents of {file}.', 'I’m checking how {file} is organized.',
    'Let me get the lay of the land in {file}.', 'I’ll browse the files under {file}.',
    'Let me see how this directory is arranged.', 'I’m reviewing the project structure here.',
    'Let me check what files are available.', 'I’ll explore this part of the workspace.',
    'Let me get a quick overview of {file}.', 'I’m looking through the directory tree.',
    'Let me look through {file}.', 'I’ll inspect the folders in {file}.',
    'Let me see what we have to work with here.', 'I’m taking stock of the files in {file}.',
  ],
  search_files: [
    'Searching for the relevant code.', 'Checking the matching references.',
    'Checking this in the codebase.', 'Locating the implementation.',
    'Checking where this is used.', 'Finding the code path.',
  ],
  git_commit_compose: [
    'Let me draft a commit message.', 'I’ll prepare a commit message for you.',
    'Let me summarize these changes for the commit.', 'I’m putting together a clear commit message.',
    'Let me write up the commit summary.', 'I’ll draft a concise message for these changes.',
    'Let me turn this work into a commit message.', 'I’m preparing the Source Control message now.',
    'Let me capture the intent of these changes.', 'I’ll compose a commit message that reflects the work.',
  ],
  invoke_summary: [
    'Let me pull up the summary for {file}.',
    'I\'ll open the overview for {file}.',
    'Let me bring up {file}.',
    'I\'ll show you the summary of {file}.',
    'Opening the summary for {file}.',
  ],
  run_terminal_command: [
    'I need your approval to run this.',
    'Can you approve this command',
  ],
};
